version: '3.8'

services:

  mongo:
    container_name: mongo
    image: mongo:6.0.2
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_AUTH_DB}
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_ROOT_USER}:${MONGO_ROOT_PASSWORD}@mongo:27017/ #mongo://rootUser:examplePassword@mongo:27017/

  redis:
    image: redis
    ports:
      - "63792:6379"
    restart: always

  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8082:8082"

  job-offers:
    container_name: job-offers
    #build: .
    image: 211125674580.dkr.ecr.eu-central-1.amazonaws.com/job-offers:latest
    restart: always
    ports:
      - '8000:8080'
    environment:
      MONGO_USER: ${MONGO_APP_USER}
      MONGO_PASSWORD: ${MONGO_APP_PASSWORD}
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_DB_NAME: ${MONGO_DB_NAME}
      MONGO_AUTH_SOURCE: ${MONGO_AUTH_DB}
      REDIS_HOST: redis
      REDIS_PORT: 6379
