spring:
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/job-offers-web
      auto-index-creation: true
      
job-offers:
  offers-scheduler:
    fetcherRunOccurrence: PT3H
  offers-fetcher:
    http:
      client:
        config:
          uri: http://ec2-3-120-147-150.eu-central-1.compute.amazonaws.com
          port: 5057
          readTimeout: 5000
          connectionTimeout: 5000

scheduling:
  enabled: true

auth:
  jwt:
    secret: ${JWT_SECRET}
    issuer: job-offers-backend
    expiration-days: 30